import bplan from "../../images/logos/Bplan.png";
import cretonix from "../../images/logos/Cretonix.png";
import datawiz from "../../images/logos/Datawiz..png";
import enigma from "../../images/logos/Enigma.png";
import nth from "../../images/logos/NTH.png";
import rc from "../../images/logos/RC.png";
import roboliga from "../../images/logos/Roboliga.png";
import wallstreet from "../../images/logos/Wallstreet.png";
import webwaever from "../../images/logos/Web waever.png";
import xodia_new from "../../images/logos/xodia_new.png";

const EventList = [
  {
    id: 1,
    slug: "datawiz",
    title: "DATAWIZ",
    name: "DATAWIZ",
    description: `DataWiz is an online event testing participants' skills in data analysis, machine learning, and artificial intelligence using real-world datasets.`,
    date: "16th - 17th  February 2026",
    price: "50",
    timings: [
      "Round 1: 16th February 2026 - 10:00 IST",
      "Round 2: 17th February 2026 - 14:00 IST",
    ],
    prizes: ["1st Prize: Rs. 3000", "2nd Prize: Rs. 2000"],
    contact: [{ name: "Harshad Karle", number: "+91 9819381674" }],
    rules: [
      "Maintain fair play and integrity.",
      "Demonstrate best effort and innovation.",
      "Respect fellow participants and organizers.",
      "Encourage learning, collaboration, and inclusivity.",
    ],
    structure: [
      "Train the best AI/ML model possible.",
      "Clear both rounds through continuous participation.",
    ],
    logo: datawiz,
    players: "Individual Online event!",
    maxplayers: 1,
  },
  {
    id: 2,
    slug: "reverse_coding",
    title: "RC",
    name: "REVERSE CODING",
    description: `Reverse Coding is a coding competition designed to test participants' conceptual understanding of algorithms and programming languages. Participants must combine logical reasoning and agility to decipher given patterns and decode sequences to arrive at the final solution.`,
    date: "16th - 17th February 2026",
    price: "50",
    timings: [
      "Round 1: 16th February 2026 - 17:30 IST (PICT Campus - Own Laptops)",
      "Round 2: 17th February 2026 - 18:00 IST (PICT Campus)",
    ],
    prizes: ["1st Prize: Rs. 5000", "2nd Prize: Rs. 3000"],
    contact: [
      { name: "Sanavi Kulkarni", number: "+91 9890316763" },
      { name: "Swayam Gosavi", number: "+91 9822687804" },
    ],
    rules: [
      "Questions are integer-based and involve complex mathematical problems that require coding for efficient solutions.",
      "Each round consists of a 30-minute game for individuals or teams of two.",
      "Each participant/team is provided with 3 lifelines; details will be revealed during the game.",
      "Switching tabs or closing the browser during the game is prohibited and will result in automatic logout.",
      "No AI allowed at all.",
    ],
    structure: [
      "Round 1 – Logic Round: A 30-minute numerical answer-based round for individuals or teams (maximum 2 members). Questions are based on coding concepts in C/C++, Java, and Python. Participants are divided into Junior Category (FE and SE students) and Senior Category (TE and BE students). Three beneficial lifelines will be provided during the game.",
      "Round 2 – Decipher and Code Round: A 2-hour coding round where participants must solve 6 core coding problems without any lifelines. Questions will focus on Data Structures, Algorithms, and competitive programming concepts. Junior-level questions will be comparatively less challenging than senior-level questions.",
      "Judging Criteria: Evaluation will be based on the time and space efficiency of the submitted solutions within the given time constraints.",
    ],
    logo: rc,
    players: "Individual or team of 2 players",
    maxplayers: 2,
  },
  {
    id: 3,
    slug: "web_weaver",
    title: "WEB WEAVER",
    name: "WEB WEAVER",
    description: `PISB introduces WebWeaver, a hackathon where innovation meets competition. Participants create innovative solutions and compete in exciting challenges for substantial rewards.`,
    date: "16th - 18th February 2026",
    price: "0",
    timings: [
      "Idea submission deadline: 13th February 2026",
      "Result announcement: 16th February 2026",
      "Final round: 18th February 2026 - 18:30 (Offline)",
    ],
    prizes: ["1st Prize: Rs. 3000", "2nd Prize: Rs. 2000"],
    contact: [
      { name: "Gargi Rahane", number: "+91 9970145767" },
      { name: "Shravan Upadhye", number: "+91 7972585231" },
    ],
    rules: [
      "Each team can consist of a maximum of 4 members.",
      "Problem statements and submission form links are provided in the Info section.",
      "For the first round, participants need to submit their idea about the problem statement in PPT or PDF.",
      "For the idea submission round, submission of a PPT is mandatory; prototype submission is optional.",
      "Use of ready-made templates is not allowed.",
      "All submissions must be made before the deadline; late entries will not be considered.",
      "Teams selected after the evaluation round must be present for the final presentation on 18th February 2026.",
      "The decision of the judges will be final and binding.",
    ],
    structure: [
      "Idea Submission Round: Participants must upload PPT/PDF explaining their approach, optional prototype, and a video explanation. Submission via Google Form.",
      "Evaluation Round: Results will be announced on 16th February 2026.",
      "Final Round: Shortlisted teams present their final solution offline at PICT, Pune on 18th February 2026 before the judges.",
    ],
    logo: webwaever,
    players: "Team of 2-4 players",
    maxplayers: 4,
  },
  {
    id: 4,
    slug: "oss",
    title: "MERGE CONFLICT",
    name: "Merge Conflict",
    description: `Merge Conflict is an individual contribution-based event where participants collaborate on real-world open source projects.

Contributions are evaluated based on quality, complexity, and adherence to standard open source workflows.`,
    date: "1st February – 17th February",
    price: "0",
    timings: [
      "Event Duration: 1st February to 17th February",
      "Final Results: Based on leaderboard standings",
    ],
    prizes: ["1st Prize: Rs. 5000", "2nd Prize: Rs. 3000"],
    contact: [{ name: "Maitreya Vaidya", number: "+91 8669959399" }],
    rules: [
      "Participants may contribute to multiple projects (Projects Link is given in info)",
      "Issues must be officially assigned by a Mentor or Project Admin before work begins",
      "Contributions without assignment will not be considered",
      "Only meaningful and non-trivial contributions are allowed",
      "Starring the repository is mandatory for eligibility",
      "Plagiarized work will result in immediate disqualification",
      "All contributions must be original and uniquely crafted",
    ],
    structure: [
      "Create or request assignment for an issue",
      "Start work only after assignment approval",
      "Create a separate branch for each issue",
      "Submit pull requests only for assigned issues",
      "Address mentor feedback promptly",
      "Points are awarded based on issue difficulty:",
      "HARD ISSUE – 30 POINTS",
      "MEDIUM ISSUE – 20 POINTS",
      "EASY ISSUE – 10 POINTS",
      "Points may be increased or decreased after review of merged pull requests",
    ],
    logo: "assets/icons/merge_conflict.png",
    players: "Individual Online Event",
    maxplayers: 1,
  },
  {
    id: 5,
    slug: "cretronix",
    title: "CRETRONIX",
    name: "CRETRONIX",
    description: `Cretronix tests participants' knowledge in electronics, physics, logic, and circuit design through theoretical challenges and hands-on implementation.`,
    date: "16th - 17th February 2026",
    price: "50",
    timings: [
      "Round 1: 16th February 2026 - 17:30 IST (PICT Campus: A3 010)",
      "Round 2: 17th February 2026 - 16:00 IST (PICT Campus: A3 101)",
    ],
    prizes: ["1st Prize: Rs. 3000", "2nd Prize: Rs. 2000"],
    contact: [
      { name: "Chaitanya Shingate", number: "+91 8468836665" },
      { name: "Siddharth Bhole", number: "+91 8329698819" },
    ],
    rules: [
      "Maximum 2 members per team.",
      "Late arrivals will be disqualified.",
      "Datasheets and calculators are allowed.",
      "Mobile phones are strictly prohibited.",
      "Participants must submit a circuit working document.",
    ],
    structure: [
      "Categories: Junior (FE/SE) and Senior (TE/BE)",
      "Round 1 – 15 theoretical/practical questions (60 minutes)",
      "Top teams qualify for Round 2",
      "Round 2 – Hardware-based circuit implementation",
    ],
    logo: cretonix,
    players: "Individual or team of 2 players",
    maxplayers: 2,
  },
  {
    id: 6,
    slug: "xodia",
    title: "XODIA",
    name: "XODIA",
    description:
      "Dive into the realm of bot development with Xodia, where participants craft intelligent bots using reinforcement learning techniques or algorithms to compete head-to-head in an exhilarating gaming environment. Let the games begin!",

    date: "16th – 18th February 2026",
    price: "50",
    timings: [
      "Game environment release: 16th February 2026 - 06:00 IST",
      "Solution submission deadline: 18th February 2026 - 23:59 IST",
    ],
    prizes: ["1st Prize: Rs. 5000", "2nd Prize: Rs. 3000"],
    contact: [
      {
        name: "Malhar Inamdar",
        number: "+91 7499414493",
      },
    ],
    rules: [
      "The game environment for the competition will be a Reinforcement Learning–based multi-universe game inspired by Stranger Things.",

      "THE CHALLENGE:\n" +
      "Universe 1: Play as Eleven, rescue Will from the Upside Down's darkest corners\n" +
      "Universe 2: Lead Steve, Robin & Dustin through a Russian-blocked Hawkins Lab heist\n" +
      "Universe 3: Face VECNA in an epic multi-directional combat showdown!",

      "Bots must be submitted in the standard submission format (to be shared) before the specified deadline.",
      "The submission of each team/participant will be streamed.",
      "This competition focuses on learning efficiency, adaptability, and decision-making.",
    ],
    structure: [
      "The competition consists of a single round, with winners decided by maximum points achieved.",
    ],
    logo: xodia_new,
    players: "Individual or team of 2 players",
    maxplayers: 2,
  },
  {
    id: 7,
    slug: "nth",
    title: "NTH",
    name: "NETWORK TREASURE HUNT",
    description: `Network Treasure Hunt (NTH) is a 24-hour online puzzle challenge. You have the internet at your fingertips - use whatever tools, resources, and approaches you like - to solve as many questions as you can within the time limit. Each answer leads to the next, and progress depends entirely on how well you think, search, and connect the dots.`,
    date: "14th - 15th February 2026",
    price: "0",
    timings: [
      "Event Start: 14th February 2026 - 21:00 IST",
      "Event End: 15th February 2026 - 21:00 IST",
    ],
    prizes: ["1st Prize: Rs. 5000", "2nd Prize: Rs. 3000"],
    contact: [{ name: "Instagram", number: "@nth__live" }],
    rules: [
      "Questions may include images, videos, GIFs, audio clips, and text-based clues.",
      "Answers must be submitted by modifying the URL in the following format: nth.credenz.co.in/question/put_your_answer_here",
      "A correct answer redirects you to the next question; an incorrect answer reloads the current one.",
      "The leaderboard displays the top scorers in real time.",
      "Correct answers award keys, which can be used to unlock hints for your current question.",
      "Keys are limited—use them wisely.",
      "After 24 hours, the participant/team at the top of the leaderboard is declared the winner.",
      "Participants (team or individual) must use only one account throughout the event.",
      "Any violation of rules may result in disqualification.",
      "The decision of the organizers is final.",
      "For assistance, consult the Help section first. Contact Instagram @nth__live only if necessary.",
      "Teams may consist of any number of members, but gameplay must be done through a single account.",
    ],
    structure: [
      "The event begins exactly at 9:00 PM on the official event website.",
      "Participants can register on nth.credenz.co.in anytime before or during the event.",
      "The hunt remains live for 24 hours, and participants may join or continue playing at any point during this window.",
      "Progress is saved automatically, allowing players to resume from where they left.",
      "The leaderboard updates in real time based on progress and score.",
      "In case of difficulties, participants must first refer to the Help section BEFORE contacting the organizers via Instagram: @nth__live.",
    ],
    logo: nth,
    players:
      "Individual or Team event! (Visit @nth_live on Instagram for participation details)",
    maxplayers: 1,
  },
  {
    id: 8,
    slug: "enigma",
    title: "ENIGMA",
    name: "ENIGMA",
    description: `Are you diligent enough to face mind-boggling questions that push your logical reasoning to its limits? Enigma is the perfect challenge to test your aptitude, thinking capability, response time, and mental agility.`,
    date: "16th - 17th February 2026",
    price: "50",
    timings: [
      "Round 1: 16th February 2026 - 18:15 IST",
      "Round 2: 17th February 2026 - 17:00 IST",
    ],
    prizes: ["1st Prize: Rs. 3000", "2nd Prize: Rs. 2000"],
    contact: [
      { name: "Rishabh Sharma", number: "+91 8459677560" },
      { name: "Darshan Wagh", number: "+91 9529868650" },
    ],
    rules: [
      "Use of electronic gadgets such as mobile phones, calculators, and smartwatches is strictly prohibited.",
      "Round 1 is a 30-minute aptitude test.",
      "Round 2 consists of a two-hour descriptive logical reasoning interview.",
      "Enigma Wildcard is conducted exclusively for PICT students; winners are directly promoted to Round 2 free of cost.",
    ],
    structure: [
      "Enigma is a logical reasoning-based competition.",
      "The event evaluates aptitude, analytical thinking, response time, and mental ability.",
      "Participants must be prepared to put their grey cells to work!",
    ],
    logo: enigma,
    players: "Individual or team of 2 players",
    maxplayers: 2,
  },
  {
    id: 9,
    slug: "wallstreet",
    title: "WALLSTREET",
    name: "WALLSTREET",
    description: `"The stock market is a device for transferring money from the impatient to the patient." – Warren Buffett. Interested in learning about the stock market and improving your investment skills? Wall Street is a virtual stock market simulation that allows participants to experience trading, investment strategies, and market dynamics in a risk-free environment.`,
    date: "16th - 18th February 2026",
    price: "50",
    timings: [
      "Day 1: 16th February 2026 - 09:00 IST to 15:00 IST",
      "Day 2: 17th February 2026 - 09:00 IST to 15:00 IST",
      "Day 3: 18th February 2026 - 09:00 IST to 15:00 IST",
    ],
    prizes: ["1st Prize: Rs. 5000", "2nd Prize: Rs. 3000"],
    contact: [
      { name: "Ashwin Ketkar", number: "+91 7620594657" },
      { name: "Darshan Wagh", number: "+91 9529868652" },
    ],
    rules: [
      "Each participant will be provided with a unique ID and password to log in to the Wall Street website.",
      "Participants must buy stocks and subscribe to IPOs using the provided virtual cash.",
      "IPOs will be floated daily before the start of trading sessions.",
      "IPO allocation will be visible on the first trading day and will follow a first-come, first-served basis.",
      "The market opens at 9:00 AM on the first day, displaying all stocks with their listing prices.",
      "The market will be active from 9:00 AM to 3:00 PM for three days; each session is considered one trading day.",
      "Buy bids or sell asks must be rounded to the current price range (e.g., if price is 100.78, bids must be between 100 and 101).",
      "Rankings are decided using a valuation formula: 60% of total asset value in shares (current market price) + 40% of remaining cash balance.",
      "Participants may be disqualified in case of any malpractices.",
      "News related to listed companies will be displayed 15 minutes before trading begins.",
    ],
    structure: [
      "Wall Street is a virtual stock market simulation.",
      "Participants can experiment with different trading strategies without using real money.",
      "Performance is evaluated based on portfolio valuation and cash balance.",
    ],
    logo: wallstreet,
    players: "Individual Online event!",
    maxplayers: 1,
  },
  {
    id: 10,
    slug: "roboliga",
    title: "ROBOLIGA",
    name: "ROBOLIGA",
    description: `For those passionate about robotics and seeking an adrenaline-fueled challenge, ROBOLIGA offers an exciting platform. Bring your innovative robotic creations and football skills to the field, where bots compete in a thrilling showdown showcasing speed, agility, and strategic excellence.

Online registrations closed. On Spot registrations: 500 Rs, please contact the numbers mentioned.`,
    date: "16th February 2026",
    price: "0",
    timings: ["16th February 2026 - 17:00 IST","17th February 2026 - 15:30 IST"],
    prizes: ["1st Prize: Rs. 11000", "2nd Prize: Rs. 6000"],
    contact: [
      { name: "Bhavika Panpalia", number: "+91 9702050408" },
      { name: "Ansh Shah", number: "+91 7775033356" },
    ],
    rules: [
      "A maximum of 3 undergraduate students are allowed per team.",
      "Intentional damage to opponent robots (wires, wheels, motors, etc.) is prohibited.",
      "Any damage to the field or opponent robot will result in immediate disqualification.",
      "Multiple teams from the same college are allowed.",
      "The robot must comply with the specified robot limitation criteria.",
      "Teams may register at college registration desks or at the event desk at least one hour prior to the event.",
      "All participants must carry valid institute ID cards at all times.",
      "Robot Limitations:",
      "Maximum dimensions: 30 cm × 30 cm × 30 cm.",
      "Maximum weight: 2.5 kg.",
      "Power specifications: Maximum voltage of 12V (normal operation).",
      "Teams must bring their own batteries sufficient for the entire day.",
      "The robot must not split into independent parts.",
      "Robot control can be manual (wireless) or automatic.",
      "No weapons such as blades or spikes are allowed.",
      "Any number of actuators may be used.",
      "One robot cannot be shared between two teams.",
      "Judging Criteria:",
      "A yellow card is issued for hand touch after the first instance; three yellow cards lead to a red card (disqualification).",
      "Organizers may disqualify teams for misconduct or disorderly behavior.",
      "Organizers reserve the right to modify the field design without prior notice.",
      "The organizers' decision will be final and binding.",
    ],
    structure: [
      "Match:",
      "Each match lasts 4 minutes, divided into two halves of 2 minutes each.",
      "A 30-second halftime break is provided for robot adjustments.",
      "Matches are one-on-one between randomly selected teams.",
      "The team with the highest score wins; ties are resolved via penalty shootouts.",
      "The tournament format may include league stages and playoffs.",
      "League matches are non-knockout rounds.",
      "Scoring System:",
      "Elimination Round:",
      "- Goal from inner circle – +20 points",
      "- Goal from between inner circle and half line – +40 points",
      "- Goal from beyond half line – +60 points",
      "- Yellow Card – Points deduction",
      "- Red Card – Disqualification",
      "Final Round: Scoring details will be announced on the website after elimination rounds.",
    ],
    logo: roboliga,
    players: "Team Event!",
    maxplayers: 3,
  },
  {
    id: 11,
    slug: "b_plan",
    title: "B-PLAN",
    name: "B-PLAN",
    description: `Put your logical, aptitude, business knowledge, and analytical skills to the test in B-Plan. This event challenges participants through time-bound rounds involving problem-solving, decision-making, ideation, and impactful presentations.`,
    date: "17th February 2026",
    price: "50",
    timings: [
      "Round 1: 17th February 2026 - 16:00 IST",
      "Round 2: 18th February 2026 - 14:30 IST",
    ],
    prizes: ["1st Prize: Rs. 5000", "2nd Prize: Rs. 3000"],
    contact: [
      { name: "Ayush Changle", number: "+91 9527144180" },
      { name: "Rutuj Desale", number: "+91 9881042699" },
    ],
    rules: [
      "Use of smart gadgets and mobile phones is strictly prohibited during the event.",
      "Participants must report at least 20 minutes before the scheduled time.",
      "Any form of malpractice will lead to immediate disqualification.",
    ],
    structure: [
      "Aptitude Round (Round 1): Individual round containing questions on data interpretation, basic aptitude, and business-oriented concepts including stock and share markets.",
      "Shark Tank Round (Round 2): Qualified teams will receive random business pitches and must present them before a panel of judges (sharks), who will evaluate pitching and decision-making skills to determine the winners.",
    ],
    logo: bplan,
    players: "Individual or team of 2 players",
    maxplayers: 2,
  },
];

export default EventList;
